% Load stats table
stats = readtable('C:\Users\ryous\Downloads\audio-qa-automation\data\processed\stats.csv');

features = [ ...
    stats.dynamic_range_db, ...
    stats.onset_peak_ratio, ...
    stats.centroid_p95, ...
    stats.zcr_p95, ...
    stats.rms_mean, ...
    stats.silence_ratio ...
];

R = corrcoef(features);

figure;
imagesc(R);
colorbar;

title('Correlation Matrix of Audio Features');

xticks(1:6);
yticks(1:6);

xticklabels({ ...
    'DynamicRange', ...
    'OnsetPeak', ...
    'Centroid', ...
    'ZCR', ...
    'RMS', ...
    'Silence' ...
});

yticklabels({ ...
    'DynamicRange', ...
    'OnsetPeak', ...
    'Centroid', ...
    'ZCR', ...
    'RMS', ...
    'Silence' ...
});

axis square;
