% Clean slate
clear; clc;

% Load stats table
stats = readtable('C:\Users\ryous\Downloads\audio-qa-automation\data\processed\stats.csv');

% Scatter plot: Dynamic Range vs Onset Peak Ratio
figure;
scatter(stats.dynamic_range_db, stats.onset_peak_ratio, 'filled');

xlabel('Dynamic Range (dB)');
ylabel('Onset Peak Ratio');
title('Dynamic Range vs Transient Strength');
grid on;

% Interpretation box
annotation('textbox', [0.62 0.75 0.3 0.15], ...
    'String', { ...
        'Interpretation:', ...
        'High DR + High Onset = Healthy dynamics', ...
        'Low DR + Low Onset = Over-compression', ...
        'Weak trend = Feature mismatch' ...
    }, ...
    'FitBoxToText','on', ...
    'BackgroundColor','black');

% Scatter plot: Brightness vs Noise
figure;
scatter(stats.centroid_p95, stats.zcr_p95, 'filled');

xlabel('Spectral Centroid (95th Percentile)');
ylabel('ZCR (95th Percentile)');
title('Brightness vs Noise');
grid on;

annotation('textbox', [0.62 0.75 0.3 0.15], ...
    'String', { ...
        'Interpretation:', ...
        'High centroid + Low ZCR = Clean brightness', ...
        'High centroid + High ZCR = Harsh / noisy', ...
        'Strong correlation = Possible redundancy' ...
    }, ...
    'FitBoxToText','on', ...
    'BackgroundColor','black');

% Scatter plot: RMS Mean vs Silence Ratio
figure;
scatter(stats.rms_mean, stats.silence_ratio, 'filled');

xlabel('Mean RMS Energy');
ylabel('Silence Ratio');
title('Energy vs Silence Ratio');
grid on;

annotation('textbox', [0.62 0.75 0.3 0.15], ...
    'String', { ...
        'Interpretation:', ...
        'High RMS + Low Silence = Consistent energy', ...
        'Low RMS + High Silence = Sparse audio', ...
        'High RMS + High Silence = Gating artifact' ...
    }, ...
    'FitBoxToText','on', ...
    'BackgroundColor','black');

